### ISSUE TITLE
processTransitions method broken?

### ISSUE THREAD

**Issue by ollieh-m** [sharetribe/sharetribe-sdk-js#83]
I've been unable to call sdk.processTransitions.query() successfully. The request it submits doesn't include the params I pass into the function. On digging a bit, I can see the params that arrive at the doRequest() function look like this:
```
{"~:transaction_id":"~u5b290e7e-f09c-4783-bea1-afdf7bf6d852","~:foo":"bar"}
```

But if I log out the params that arrive by calling the sdk.messages.query() function, they look like this:
```
{transaction_id: UUID, foo: "bar"}
```

To clarify, the only difference between what I am calling is the name of the endpoint: `sdk.messages.query({transaction_id: txId, foo: 'bar'})` vs   `sdk.processTransitions.query({transaction_id: txId, foo: 'bar'})`

So the question is where the `~:` is coming from at the beginning of the param keys and the transaction ID and how do I use the processTransitions endpoint properly.

Thanks!

**Comment by ovan** [comment]
@ollieh-m Thanks for reporting. I was able to repro and also noticed the API docs are a little out of date. I'll get this fixed tomorrow.

**Comment by ollieh-m** [comment]
Thanks for the prompt fix!

**Comment by ovan** [comment]
@ollieh-m no prob. Thanks again for spotting this. There was a bug in encoding and that's now fixed in latest master. I also updated the API docs here: https://flex-api-docs-preview.sharetribe.com/#query-transitions. The parameters part was out of date. Now you need to always pass either `transactionId` or `processAlias`. That way you can explore the entire process (with the combination of `processAlias` and `lastTransition`) or query by `transactionId` to get a list of available next steps for a specific transaction.

One comment about the example code you gave in the issue. The parameter names are camelCased, not snake_cased, i.e. `sdk.processTransitions.query({transactionId: txId});`

**Comment by ollieh-m** [comment]
Cool, thanks. I was basing the param name on this from the frontend template in the TransactionPage.duck:
```
return sdk.messages
    .query({
      transaction_id: txId,
```
